//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inkluzitron.Resources.Whip {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WhipResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WhipResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inkluzitron.Resources.Whip.WhipResources", typeof(WhipResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _01 {
            get {
                object obj = ResourceManager.GetObject("_01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _02 {
            get {
                object obj = ResourceManager.GetObject("_02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _03 {
            get {
                object obj = ResourceManager.GetObject("_03", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _04 {
            get {
                object obj = ResourceManager.GetObject("_04", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _05 {
            get {
                object obj = ResourceManager.GetObject("_05", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _06 {
            get {
                object obj = ResourceManager.GetObject("_06", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _07 {
            get {
                object obj = ResourceManager.GetObject("_07", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _08 {
            get {
                object obj = ResourceManager.GetObject("_08", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _09 {
            get {
                object obj = ResourceManager.GetObject("_09", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _14 {
            get {
                object obj = ResourceManager.GetObject("_14", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _15 {
            get {
                object obj = ResourceManager.GetObject("_15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _17 {
            get {
                object obj = ResourceManager.GetObject("_17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _18 {
            get {
                object obj = ResourceManager.GetObject("_18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _19 {
            get {
                object obj = ResourceManager.GetObject("_19", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _20 {
            get {
                object obj = ResourceManager.GetObject("_20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _21 {
            get {
                object obj = ResourceManager.GetObject("_21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _22 {
            get {
                object obj = ResourceManager.GetObject("_22", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _23 {
            get {
                object obj = ResourceManager.GetObject("_23", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _24 {
            get {
                object obj = ResourceManager.GetObject("_24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _25 {
            get {
                object obj = ResourceManager.GetObject("_25", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type byte[].
        /// </summary>
        public static byte[] _26 {
            get {
                object obj = ResourceManager.GetObject("_26", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
