version: '3.9'

services:
    bot:
        build: .
        container_name: Inkluzitron
        env_file:
            - environment.env
        volumes:
            - /home/janch32/inkluzitron:/data
        mem_limit: 500m
